#!/usr/bin/env bash
# PropFlow — Version Bump & Release Pipeline
# Usage: bash scripts/version-bump.sh [patch|minor|major] 'Summary of changes'
# Example: bash scripts/version-bump.sh patch 'Fix Save button touch target on mobile'
#
# This script runs the complete release pipeline:
#   1. Full regression test suite (must pass — zero failures)
#   2. npm version bump (updates package.json + creates git tag)
#   3. Write src/lib/version.ts and public/version.json
#   4. Update CHANGELOG.md (moves [Unreleased] to versioned entry)
#   5. Commit everything with the release message
#   6. Push commit + tag to GitHub
#   7. Create a GitHub Release
#   8. Send ntfy notification with GitHub URL + Tailscale test URL

set -euo pipefail

BUMP_TYPE="${1:-patch}"
SUMMARY="${2:-Release}"

# Step 1: Full regression — zero failures required
echo '--- Running full regression before version bump ---'
npm run test:regression || {
  echo 'REGRESSION FAILED: Fix all failing tests before bumping version.'
  bash scripts/notify.sh 'PropFlow — Release Blocked' \
    "Version bump blocked: regression failed. Fix tests first." 4 'x,rotating_light'
  exit 1
}
echo '--- All tests passing. Proceeding. ---'

# Step 2: Bump version in package.json (no git tag yet — we do it ourselves)
npm version "$BUMP_TYPE" --no-git-tag-version
NEW_VERSION=$(node -p "require('./package.json').version")
GIT_TAG="v$NEW_VERSION"
RELEASE_DATE=$(date -u +%Y-%m-%d)

# Step 3: Write version.ts for UI components
mkdir -p src/lib
cat > src/lib/version.ts << TSEOF
// Auto-generated by scripts/version-bump.sh — do not edit manually.
// Source of truth is package.json version field.
export const APP_VERSION    = '${NEW_VERSION}';
export const RELEASE_DATE   = '${RELEASE_DATE}';
export const GITHUB_RELEASE = 'https://github.com/mdarifuzzaman1116/propflow-app/releases/tag/${GIT_TAG}';
TSEOF

# Write public/version.json for external polling (monitoring tools, status pages)
mkdir -p public
cat > public/version.json << JSONEOF
{"version":"${NEW_VERSION}","releaseDate":"$(date -u +%Y-%m-%dT%H:%M:%SZ)","githubRelease":"https://github.com/mdarifuzzaman1116/propflow-app/releases/tag/${GIT_TAG}"}
JSONEOF

# Step 4: Move [Unreleased] entries to versioned section in CHANGELOG.md
node scripts/update-changelog.js "$NEW_VERSION" "$BUMP_TYPE"

# Step 5: Stage and commit everything
git add package.json src/lib/version.ts public/version.json CHANGELOG.md \
        TESTING.md PROMPTS.md SESSION.md
git commit -m "chore: release ${GIT_TAG} — ${SUMMARY}"
git tag -a "$GIT_TAG" -m "Release ${GIT_TAG}: ${SUMMARY}"

# Step 6: Push to GitHub
git push origin main --tags

# Step 7: Create GitHub Release (requires gh CLI)
if command -v gh &>/dev/null; then
  # Extract the release notes for this version from CHANGELOG.md
  RELEASE_NOTES=$(node -e "
    const fs = require('fs');
    const content = fs.readFileSync('CHANGELOG.md', 'utf8');
    const start = content.indexOf('## [${NEW_VERSION}]');
    const nextVersion = content.indexOf('\n## [', start + 1);
    const section = content.slice(start, nextVersion === -1 ? undefined : nextVersion);
    console.log(section);
  ")
  gh release create "$GIT_TAG" \
    --title "PropFlow ${GIT_TAG}" \
    --notes "$RELEASE_NOTES" \
    --repo mdarifuzzaman1116/propflow-app
fi

# Step 8: Count total passing tests for notification
TOTAL_TESTS=$(grep -c '\[PASS\]' TESTING.md 2>/dev/null || echo '?')
TAILSCALE_IP=$(tailscale ip -4 2>/dev/null || echo 'localhost')
GITHUB_URL="https://github.com/mdarifuzzaman1116/propflow-app/releases/tag/${GIT_TAG}"

bash scripts/notify.sh \
  "PropFlow ${GIT_TAG} Released" \
  "${SUMMARY} | ${TOTAL_TESTS} tests passing | GitHub: ${GITHUB_URL}" \
  3 \
  'rocket,white_check_mark'

echo ""
echo "Released PropFlow ${GIT_TAG} successfully."
echo "GitHub: ${GITHUB_URL}"
echo "Test:   http://${TAILSCALE_IP}:3000"
